[tool.poetry]
name = "openbb-empty-provider"
version = "0.0.1"
description = "Empty provider extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_empty_provider" }]

[tool.poetry.dependencies]
python = "^3.9,<3.13"
openbb-core = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
empty = "openbb_empty_provider:empty_provider"
