[tool.poetry]
name = "openbb-empty"
version = "1.0.0"
description = "An Empty OpenBB Container For Local Development"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb" }]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
notebook = "^7.2"
nbclassic = "^1.1"
jedi-language-server = "^0.41" 
openbb-core = "^1.3.0"
openbb-devtools = "^1.3.0"
openbb-charting = { version = "^2.2.0", optional = true }
openbb-empty-obbject = { path = "./extensions/empty_obbject_extension", develop = true }
openbb-empty-provider = { path = "./extensions/empty_provider_extension", develop = true }
openbb-empty-router = { path = "./extensions/empty_router_extension", develop = true }

[tool.poetry.extras]
charting = ["openbb-charting"]

all = [
    "openbb-charting",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
